### ISSUE TITLE
cannot link directly to a specific header information

### ISSUE THREAD

**Issue by cdeath** [OWASP/www-project-secure-headers#167]
problem:
when linking to a specific header information like:
https://owasp.org/www-project-secure-headers/#x-permitted-cross-domain-policies
you can't see it right away because the `Response Headers` tab is not selected.

cause:
tab selection by url also uses a fragment and you can't have both fragments in the url:
https://owasp.org/www-project-secure-headers/#div-headers

possible solutions:

move tab selection to query string:
https://owasp.org/www-project-secure-headers/?tab=response-headers#x-permitted-cross-domain-policies

or slug:
https://owasp.org/www-project-secure-headers/response-headers/#x-permitted-cross-domain-policies

**Comment by righettod** [comment]
Hi @cdeath ,

🤝 Thanks a lot for the issue.

💡 Indeed, due to the templating used for all OWASP sites, we have setup the following convention & system for direct linking. It is documented into the **Case Studies** tab:

![image](https://github.com/OWASP/www-project-secure-headers/assets/1573775/0b7f814a-0eb0-403f-81dc-b9294e66ed91)

🌏 Example:

https://owasp.org/www-project-secure-headers/index.html#div-headers_referrer-policy

👨‍💻 Debugging:

![image](https://github.com/OWASP/www-project-secure-headers/assets/1573775/946ea66a-bf19-474e-8fdd-c006a2805d53)

**Comment by cdeath** [comment]
thanks for the reply!

did not read the case studies tab. (i'm sure others might miss it too)

just wasn't expecting this behaviour.

just a thought:
i'm guessing this is static... but, since you have to parse the hash anyway... and so you don't have to change the templates
maybe you could set this up with rewrite rules? point everything to index.html, then grab the active tab from the url path...

anyway, thanks again. i'll update my links.

**Comment by righettod** [comment]
> thanks for the reply!

You are welcome 🤗

> did not read the case studies tab. (i'm sure others might miss it too)

Very good point, I will add a ref to handle that 👍  

> just a thought: i'm guessing this is static... but, since you have to parse the hash anyway... and so you don't have to change the templates maybe you could set this up with rewrite rules? point everything to index.html, then grab the active tab from the url path...

Good idea, the only issue is that we (project level)  have only access to client side processing due to the way in which deployment is made. It is why I create such client side linking system 😉

**Comment by righettod** [comment]
Handled via https://github.com/OWASP/www-project-secure-headers/pull/169
